#!/bin/bash

# Program to add new user
# read -r // usuwa widocznosc
# uruchomic za pomocą sudo

sudo useradd -p $(openssl passwd -1 $2) $1

mkdir /home/$1
mkdir /home/$1/{Deskop,Download,Picture,Templates,Documens,Music,Public,Video}

chown -R test:PR /home/$1
